/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.TextClient;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Jan
 */
public class TextClientGUI extends javax.swing.JFrame {
    
    private TextClient client;

    /**
     * Creates new form TextCientGUI
     */
    public TextClientGUI() {
        initComponents();
        client = new TextClient(taContent, lbConnectedUsers);
        taContent.setEditable(false);
        btClose.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plSettings = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taContent = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btConnect = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        lbConnectedUsers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plSettings.setBorder(javax.swing.BorderFactory.createTitledBorder("Text-Content"));
        plSettings.setLayout(new java.awt.BorderLayout());

        taContent.setColumns(20);
        taContent.setRows(5);
        taContent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onChangeText(evt);
            }
        });
        jScrollPane1.setViewportView(taContent);

        plSettings.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(plSettings, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("File"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        btConnect.setText("Connect");
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onConnect(evt);
            }
        });
        jPanel1.add(btConnect);

        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClose(evt);
            }
        });
        jPanel1.add(btClose);

        lbConnectedUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbConnectedUsers);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onConnect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onConnect
        taContent.setEditable(true);
        btClose.setEnabled(true);
        String fileName = JOptionPane.showInputDialog(this, "Filenamen eingeben", JOptionPane.INFORMATION_MESSAGE);
        plSettings.setBorder(new TitledBorder(fileName));
        plSettings.updateUI();
        
        try {
            client.connect();
            client.update("file/" + fileName);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onConnect
    
    private void onClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClose
        try {
            client.disconnect();
            btClose.setEnabled(false);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        plSettings.setBorder(new TitledBorder("Text-Content"));
        taContent.setEditable(false);
        lbConnectedUsers.setText("" + 0);
    }//GEN-LAST:event_onClose
    
    private void onChangeText(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onChangeText
        String content = taContent.getText();
        try {
            client.update(content);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onChangeText

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btConnect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConnectedUsers;
    private javax.swing.JPanel plSettings;
    private javax.swing.JTextArea taContent;
    // End of variables declaration//GEN-END:variables
}
